[package]
name = "rocket_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastrand = "1.8.0"
mongodb = "2.3.0"
rocket = "0.5.0-rc.2"
serde = "1.0.144"
