[package]
name = "redis_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
redis = { version = "0.22.2", features = ["tokio-comp", "serde", "serde_json"] }
